apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
data:
  # Base64 encoded values (change these in production!)
  # To generate: echo -n 'your-value' | base64
  postgres-user: cGV0Y2xpbmljCg==
  postgres-password: cGV0Y2xpbmljCg==
