apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: default
  labels:
    app: petclinic
type: Opaque
stringData:
  postgres_user: "petclinic"
  postgres_password: "your_secure_password_here"