apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
data:
  # Base64 encoded values
  # postgres-user: petclinic (cGV0Y2xpbmljCg==)
  # postgres-password: petclinic (cGV0Y2xpbmljCg==)
  postgres-user: cGV0Y2xpbmljCg==
  postgres-password: cGV0Y2xpbmljCg==
